# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-14 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='local',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='destino',
            field=models.ForeignKey(blank=True, db_column='destino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destino', to='app.Local'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='origen',
            field=models.ForeignKey(blank=True, db_column='origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='origen', to='app.Local'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.CharField(blank=True, default=datetime.datetime(2019, 10, 14, 16, 25, 18, 119936), max_length=1000, null=True),
        ),
    ]
