# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-14 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='origen',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 14, 20, 4, 34, 903332), max_length=1000, null=True),
        ),
    ]
