# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-14 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191014_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='origen',
            field=models.ForeignKey(blank=True, db_column='prenda_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prenda_origen', to='app.Local'),
        ),
        migrations.AddField(
            model_name='prenda',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_column='ubicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ubicacion', to='app.Local'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 14, 20, 5, 0, 302592), max_length=1000, null=True),
        ),
    ]
