# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-14 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191014_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='origen',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='_origen',
            field=models.ForeignKey(blank=True, db_column='origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_origen', to='app.Local'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 14, 15, 59, 51, 34282), max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='color',
            field=models.ForeignKey(blank=True, db_column='color', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='color', to='app.Color'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='modelo',
            field=models.ForeignKey(blank=True, db_column='modelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modelo', to='app.Modelo'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='origen',
            field=models.ForeignKey(blank=True, db_column='prenda_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='origen', to='app.Local'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='talla',
            field=models.ForeignKey(blank=True, db_column='talla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='talla', to='app.Talla'),
        ),
    ]
