# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-16 01:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191015_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='bono',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prenda',
            name='precio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 15, 20, 24, 21, 659017), max_length=1000, null=True),
        ),
    ]
