# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-16 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191015_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 15, 20, 28, 45, 145272), max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='bono',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='precio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
