# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-16 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191015_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 15, 20, 28, 47, 527578), max_length=1000, null=True),
        ),
    ]
