# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-16 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191015_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='boleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 15, 20, 30, 35, 347140), max_length=1000, null=True),
        ),
    ]
