# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-16 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191015_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 15, 20, 32, 6, 290491), max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='boleta',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
