# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-18 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191016_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 17, 19, 1, 11, 243669), max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='modelo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
