# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-18 00:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191017_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='nombre_modelo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 17, 19, 2, 40, 559599), max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='modelo',
            field=models.ForeignKey(blank=True, db_column='modelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modelo', to='app.Modelo'),
        ),
    ]
