# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-18 00:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191017_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 17, 19, 2, 44, 601071), max_length=1000, null=True),
        ),
    ]
