# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-19 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191019_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='sin_codigo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 14, 7, 40, 647335), max_length=1000, null=True),
        ),
    ]
