# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-23 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191019_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='vendedora2',
            field=models.ForeignKey(blank=True, db_column='vendedora2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendedora2', to='app.Vendedora'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 22, 22, 8, 30, 754317), max_length=1000, null=True),
        ),
    ]
