# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-23 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191022_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='pormayor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 22, 23, 7, 25, 45554), max_length=1000, null=True),
        ),
    ]
